### ISSUE TITLE
Error when updating webpack

### ISSUE THREAD

**Issue by daveisfera** [ali322/progress-webpack-plugin#1]
When I update `webpack`, I get the following error:
`error An unexpected error occurred: "could not find a copy of webpack to link in /Users/dlj/projects/test/node_modules/progress-webpack-plugin/node_modules".`

If I remove `progress-webpack-plugin` and update `webpack` and then put `progress-webpack-plugin` back, it works, bust just updating `webpack` results in this error.

**Comment by ali322** [comment]
webpack have been removed to peer dependencies
